### PR TITLE
Fix number of replicas for recommended MicroK8s

### PR DESCRIPTION
**Pull request by pauloribeiro-codacy**
Fixing the number of replicas as discussed during the "Training on K8s" meeting.

### CODE REVIEW

**Comment by h314to** [comment]
Hum... most of the components only have one replica. Only a couple of them have replicas. Maybe 1+ is more accurate than 2+, because the latter would imply that all of them have at least two replicas.

**Comment by pauloribeiro-codacy** [comment]
> Hum... most of the components only have one replica. Only a couple of them have two replicas, really. Maybe 1+ is more accurate than 2+, because the latter would imply that all of them have at least two replicas.

Thanks @h314to, I understand what you mean. Either way, then maybe the "Platform resources" shouldn't double, then? Should we ask only for 5.5+ vCPUs and 9.5+ GB RAM?

The values for this last row of the table should be revised, because as they are now we are asking two times for the "extra 1.5 vCPU and 1.5 GB memory for the MicroK8s platform itself running on the same machine as the Platform".

@paulopontesm, can you also have a look?

**Comment by paulopontesm** [comment]
> > Hum... most of the components only have one replica. Only a couple of them have two replicas, really. Maybe 1+ is more accurate than 2+, because the latter would imply that all of them have at least two replicas.
> 
> Thanks @h314to, I understand what you mean. Either way, then maybe the "Platform resources" shouldn't double, then? Should we ask only for 5.5+ vCPUs and 9.5+ GB RAM?
> 
> The values for this last row of the table should be revised, because as they are now we are asking two times for the "extra 1.5 vCPU and 1.5 GB memory for the MicroK8s platform itself running on the same machine as the Platform".
> 
> @paulopontesm, can you also have a look?

We are putting 2 replicas on the website and engine. That is 1 CPUs + 1.5 Gb extra

**Comment by pauloribeiro-codacy** [comment]
> > > Hum... most of the components only have one replica. Only a couple of them have two replicas, really. Maybe 1+ is more accurate than 2+, because the latter would imply that all of them have at least two replicas.
> > 
> > 
> > Thanks @h314to, I understand what you mean. Either way, then maybe the "Platform resources" shouldn't double, then? Should we ask only for 5.5+ vCPUs and 9.5+ GB RAM?
> > The values for this last row of the table should be revised, because as they are now we are asking two times for the "extra 1.5 vCPU and 1.5 GB memory for the MicroK8s platform itself running on the same machine as the Platform".
> > @paulopontesm, can you also have a look?
> 
> We are putting 2 replicas on the website and engine. That is 1 CPUs + 1.5 Gb extra

@paulopontesm please confirm if the values in my last commit are the ones you had in mind. :white_check_mark:

**Pull request merged**
