### PR TITLE
fix: Increase resource limits for codacy-tools CY-2568

### PR DESCRIPTION
**Pull request by franciscodua**

### CODE REVIEW

**Comment by franciscodua** [comment]
We had to increase the resources in our cloud environment for this service.
So, we wanted to increase the limit requirements for on-premise installations too

**Comment by pauloribeiro-codacy** [comment]
Will this affect the [cluster provisioning requirements](https://docs.codacy.com/chart/requirements/#standard-cluster-provisioning) that we list for customers who are installing Codacy Self-hosted?

**Comment by franciscodua** [comment]
@pauloribeiro-codacy we don't expect the requirements to change since we recently removed the codacy-core service from the chart and didn't reduce the requirements

**Review by machadoit — APPROVED** [review]

**Comment by machadoit** [comment]
Even if the requirements increase maybe be bit too high, we keep adding more endpoints and more responsibility for this component. So I think those look fine 👌

**Review by joaocosta-codacy — APPROVED** [review]

**Review by paulopontesm — APPROVED** [review]

**Pull request merged**
