### PR TITLE
bump: Kubernetes version 1.17 -> 1.20

### PR DESCRIPTION
**Pull request by h314to**

### CODE REVIEW

**Review by paulopontesm — APPROVED** [review]

**Comment by paulopontesm** [comment]
Can you update the docs to add the 1.20 support? They will be updated on the next release.

**Review by joaocosta-codacy — DISMISSED** [review]

**Comment by pauloribeiro-codacy** [comment]
> Can you update the docs to add the 1.20 support? They will be updated on the next release.

Also, will we be dropping support for any older versions?

https://github.com/codacy/chart/blob/bump/upgrade-k8s-version/docs/requirements.md

**Review by pauloribeiro-codacy — CHANGES_REQUESTED** [review]
> Can you update the docs to add the 1.20 support? They will be updated on the next release.

Also, will we be dropping support for any older versions?

https://github.com/codacy/chart/blob/bump/upgrade-k8s-version/docs/requirements.md

**Comment by joaocosta-codacy** [comment]
@pauloribeiro-codacy we will not be dropping support for the older versions.
We still test them through microk8s as part of the release build process.

**Review by pauloribeiro-codacy — DISMISSED** [review]

**Review by pauloribeiro-codacy — APPROVED** [review]

**Pull request merged**
